import { useState } from "react";
import { ArrowRight, CheckCircle2, ChevronRight, Globe2, LockKeyhole, Newspaper, ShieldCheck, Sparkles, Users } from "lucide-react";
import { AfricaMap, MapLegend } from "@/components/AfricaMap";
import { PspLogo } from "@/components/PspLogo";
import { Language, SiteShell } from "@/components/SiteShell";
import { trpc } from "@/lib/trpc";

const signals = [
  { value: "140+", label: "agencies entering review" },
  { value: "05", label: "integrity audit points" },
  { value: "24/7", label: "protected signal intake" },
];

const portfolios = [
  { href: "/verification", number: "01", title: "Verification Portfolio", body: "Search the White List, inspect audit scores, and verify the Digital Trust Seal before you pay or share documents.", icon: ShieldCheck, color: "emerald" },
  { href: "/protection", number: "02", title: "Protection Portfolio", body: "Learn your rights, use a pre-departure checklist, and understand the standards built to stop exploitation.", icon: Globe2, color: "blue" },
  { href: "/survivor", number: "03", title: "Survivor Hub", body: "Submit confidential intelligence through an encrypted, survivor-centered intake path with optional secure attachments.", icon: LockKeyhole, color: "gold" },
];

export default function Home() {
  const [language, setLanguage] = useState<Language>("EN");
  const news = trpc.news.latest.useQuery({ limit: 3 }, { staleTime: 240000, refetchOnWindowFocus: true });
  return <SiteShell language={language} onLanguageChange={setLanguage}>
    <main>
      <section className="relative isolate overflow-hidden bg-[#061528] py-20 text-white sm:py-28">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,rgba(57,119,199,.28),transparent_36%),linear-gradient(120deg,#061528_0%,#0a2944_55%,#071522_100%)]" />
        <div className="absolute right-[-8%] top-[-22%] h-[650px] w-[650px] rounded-full border border-[#57e6b1]/10 shadow-[0_0_160px_rgba(57,119,199,.16)]" />
        <div className="container relative grid items-center gap-14 lg:grid-cols-[1.04fr_.96fr]">
          <div className="max-w-3xl">
            <div className="mb-7 inline-flex items-center gap-3 rounded-full border border-[#d9ad3b]/30 bg-[#d9ad3b]/10 px-3 py-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#f0c95d]"><span className="grid h-5 w-5 place-items-center overflow-hidden rounded-md"><img src="/manus-storage/project-safe-passage-3d-logo_86403387.png" alt="" className="h-6 w-6 object-contain" /></span>IMI Initiative · global protection network</div>
            <h1 className="font-display text-[clamp(3rem,7vw,6.8rem)] font-semibold leading-[.93] tracking-[-.06em]">Restoring trust and integrity to <span className="text-[#57e6b1]">global migration pathways.</span></h1>
            <p className="mt-7 max-w-2xl text-base leading-7 text-slate-300 sm:text-lg">Project Safe Passage eliminates travel scams, protects aspiring youth, and establishes verified migration standards through intelligence, transparency, and survivor-led oversight.</p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="/verification" className="inline-flex items-center justify-center gap-3 rounded-full bg-[#57e6b1] px-5 py-3.5 text-xs font-bold uppercase tracking-[0.12em] text-[#062219] shadow-[0_12px_36px_rgba(87,230,177,.18)] transition hover:bg-[#80f0c5] active:scale-[.98]">Check White List Registry <ArrowRight size={16} /></a><a href="/survivor" className="inline-flex items-center justify-center gap-3 rounded-full border border-white/20 bg-white/[.04] px-5 py-3.5 text-xs font-bold uppercase tracking-[.12em] text-white transition hover:border-[#57e6b1]/60 hover:bg-white/[.08]"><LockKeyhole size={15} className="text-[#57e6b1]" /> Submit Confidential Report</a></div>
            <div className="mt-12 grid max-w-2xl gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-3">{signals.map((signal) => <div key={signal.label} className="bg-[#0a1d31]/80 px-5 py-5 backdrop-blur-sm"><p className="font-display text-3xl font-semibold text-white">{signal.value}</p><p className="mt-1 text-[10px] uppercase tracking-[.14em] text-slate-400">{signal.label}</p></div>)}</div>
          </div>
          <div className="relative mx-auto w-full max-w-[460px] lg:justify-self-end"><div className="absolute inset-10 rounded-full bg-[#57e6b1]/10 blur-3xl" /><div className="relative rounded-[34px] border border-white/10 bg-white/[.06] p-6 shadow-2xl backdrop-blur-xl"><div className="flex items-start justify-between gap-6"><PspLogo compact /><div className="text-right"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#57e6b1]">Official protection mark</p><p className="mt-2 text-xs text-slate-400">3D Digital Trust identity</p></div></div><div className="mx-auto my-8 grid aspect-square max-w-[280px] place-items-center rounded-full border border-[#d9ad3b]/30 bg-[radial-gradient(circle,#143a62_0%,#071522_68%)] p-8 shadow-[inset_0_0_70px_rgba(217,173,59,.08)]"><img src="/manus-storage/project-safe-passage-3d-logo_86403387.png" alt="Project Safe Passage official 3D shield logo" className="h-full w-full object-contain drop-shadow-[0_24px_24px_rgba(0,0,0,.45)]" /></div><div className="flex items-center justify-between border-t border-white/10 pt-5 text-[10px] uppercase tracking-[.14em] text-slate-400"><span className="inline-flex items-center gap-2"><CheckCircle2 size={14} className="text-[#57e6b1]" /> Authentic mark</span><span>PSP / 2026</span></div></div></div>
        </div>
      </section>

      <section className="bg-[#f6f9fb] py-16 sm:py-24"><div className="container"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-4 text-[10px] font-semibold uppercase tracking-[.2em] text-[#1c8d68]">One platform · four public portfolios</p><h2 className="max-w-3xl font-display text-4xl font-semibold leading-[1.04] tracking-[-.045em] text-[#10202f] sm:text-5xl">A clear path from <span className="text-[#1c8d68]">uncertainty</span> to action.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-500">Built for young people, survivors, responsible agencies, international partners, and public institutions.</p></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{portfolios.map((portfolio) => { const Icon = portfolio.icon; return <a href={portfolio.href} key={portfolio.number} className="group rounded-3xl border border-slate-200 bg-white p-6 shadow-[0_12px_35px_rgba(16,32,47,.05)] transition duration-200 hover:-translate-y-1 hover:border-[#57e6b1]/60 hover:shadow-[0_24px_50px_rgba(16,32,47,.1)] sm:p-8"><div className="flex items-center justify-between"><span className={`grid h-12 w-12 place-items-center rounded-2xl ${portfolio.color === "emerald" ? "bg-emerald-100 text-emerald-700" : portfolio.color === "blue" ? "bg-blue-100 text-blue-700" : "bg-amber-100 text-amber-700"}`}><Icon size={21} /></span><span className="font-mono text-[10px] text-slate-400">{portfolio.number} / 04</span></div><h3 className="mt-10 font-display text-2xl font-semibold text-[#10202f]">{portfolio.title}</h3><p className="mt-4 text-sm leading-7 text-slate-500">{portfolio.body}</p><span className="mt-8 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em] text-[#1c8d68]">Explore portfolio <ChevronRight size={15} className="transition group-hover:translate-x-1" /></span></a>; })}</div></div></section>

      <section className="bg-[#10202f] py-16 text-white sm:py-24"><div className="container"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-4 text-[10px] font-semibold uppercase tracking-[.2em] text-[#57e6b1]">Continental corridor intelligence</p><h2 className="max-w-3xl font-display text-4xl font-semibold leading-[1.04] tracking-[-.045em] sm:text-5xl">See where protection is <span className="text-[#57e6b1]">needed next.</span></h2></div><p className="max-w-sm text-sm leading-6 text-slate-400">Verified and monitored points across Central, West, East, North, and Southern Africa.</p></div><div className="mt-10"><AfricaMap /></div><div className="mt-5"><MapLegend /></div></div></section>

      <section className="bg-white py-16 sm:py-24"><div className="container"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="mb-4 text-[10px] font-semibold uppercase tracking-[.2em] text-[#1c8d68]">Global watch</p><h2 className="font-display text-4xl font-semibold leading-[1.04] tracking-[-.045em] text-[#10202f] sm:text-5xl">Migration risks, <span className="text-[#1c8d68]">without the noise.</span></h2><p className="mt-5 text-sm leading-7 text-slate-500">PSP monitors official migration, anti-trafficking, and route-risk reporting so citizens and partners can act on verified signals.</p><a href="/news" className="mt-7 inline-flex items-center gap-2 rounded-full border border-slate-200 px-4 py-3 text-[10px] font-bold uppercase tracking-[.14em] text-[#10202f] transition hover:border-[#57e6b1]">Open World News <ArrowRight size={14} /></a></div><div className="space-y-3">{news.isLoading ? [1, 2, 3].map((item) => <div key={item} className="h-28 animate-pulse rounded-2xl bg-slate-100" />) : news.data?.items.map((item) => <a href={item.url} target="_blank" rel="noreferrer" key={item.id} className="group flex gap-4 rounded-2xl border border-slate-200 p-5 transition hover:-translate-y-0.5 hover:border-[#57e6b1]/60 hover:shadow-lg"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#edf8f4] text-[#1c8d68]"><Newspaper size={18} /></span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2 text-[10px] font-semibold uppercase tracking-[.12em] text-[#1c8d68]"><span>{item.source}</span><span className="text-slate-300">·</span><span>{item.category}</span></span><span className="mt-2 block font-display text-lg font-semibold text-[#10202f] transition group-hover:text-[#1c8d68]">{item.title}</span></span><ArrowRight size={16} className="mt-1 shrink-0 text-slate-400 transition group-hover:translate-x-1 group-hover:text-[#1c8d68]" /></a>)}</div></div></div></section>

      <section className="bg-[#eaf4f2] py-16 sm:py-24"><div className="container"><div className="relative overflow-hidden rounded-[30px] bg-[#061528] px-6 py-12 text-white shadow-2xl sm:px-12 sm:py-16"><div className="absolute right-[-8%] top-[-50%] h-[500px] w-[500px] rounded-full border border-[#d9ad3b]/20" /><div className="relative grid gap-8 lg:grid-cols-[1fr_.7fr] lg:items-end"><div><p className="mb-4 text-[10px] font-semibold uppercase tracking-[.2em] text-[#f0c95d]">Your next safe step</p><h2 className="font-display text-4xl font-semibold leading-[1.04] tracking-[-.05em] sm:text-6xl">Verify first. <span className="text-[#57e6b1]">Move with confidence.</span></h2><p className="mt-6 max-w-xl text-sm leading-7 text-slate-400">If something feels wrong, you can report it. If an agency makes a promise, you can check it. PSP is built to make the safe path visible.</p></div><div className="flex flex-col gap-3 sm:flex-row lg:flex-col"><a href="/verification" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#57e6b1] px-5 py-3.5 text-xs font-bold uppercase tracking-[.12em] text-[#062219]">Verify an agency <ArrowRight size={15} /></a><a href="/survivor" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/15 px-5 py-3.5 text-xs font-bold uppercase tracking-[.12em] text-white">Open Survivor Hub <LockKeyhole size={14} className="text-[#57e6b1]" /></a></div></div></div></div></section>
    </main>
  </SiteShell>;
}
