import { AlertTriangle, ArrowUpRight, Database, ShieldAlert } from "lucide-react";
import type { Language } from "./SiteShell";
const content = {
  EN: { eyebrow: "Why this matters · evidence-led regional picture", title: "Migration fraud is not a single-country problem.", body: "Across Sub-Saharan Africa, deceptive recruitment, fraudulent migration promises, trafficking, and exploitation intersect with weak information, limited victim protection, and cross-border routes. PSP treats public evidence as a starting signal—not a verdict against any person or agency.", coverage: "Evidence signals across the region", caveat: "This is a curated evidence view, not a complete complaint census. Official reporting is uneven, and social-media complaints are treated as leads until independently verified.", source: "Open source", view: "View source", items: [
    ["Nigeria", "744 trafficking investigations were reported in the 2024 reporting period; the TIP report also calls for action against fraudulent labor recruiters and worker-paid recruitment fees.", "https://www.state.gov/reports/2025-trafficking-in-persons-report/nigeria"],
    ["Cameroon", "Authorities investigated 146 trafficking cases; a reported cybercrime scheme allegedly lured people with job opportunities and then subjected them to deplorable labor conditions.", "https://www.state.gov/reports/2025-trafficking-in-persons-report/cameroon"],
    ["Senegal", "The 2025 report describes fraudulent recruitment for employment abroad, forced labor and domestic servitude, and vulnerability to forced criminality in online scam operations.", "https://www.state.gov/reports/2025-trafficking-in-persons-report/senegal"],
    ["Sub-Saharan Africa", "UNODC’s 2024 regional report documents trafficking patterns across a region where cases are underreported and data quality varies by country.", "https://www.unodc.org/documents/data-and-analysis/glotip/2024/SubSaharanAfrica_GLOTIP2024.pdf"],
  ] },
  FR: { eyebrow: "Pourquoi c’est important · lecture régionale fondée sur les preuves", title: "La fraude migratoire ne concerne pas un seul pays.", body: "En Afrique subsaharienne, le recrutement trompeur, les promesses migratoires frauduleuses, la traite et l’exploitation se croisent avec le manque d’information, une protection limitée et des routes transfrontalières. PSP considère les preuves publiques comme des signaux, pas comme des verdicts.", coverage: "Signaux documentés dans la région", caveat: "Cette vue est une sélection documentée, pas un recensement complet des plaintes. Les signalements sur les réseaux sociaux restent des pistes jusqu’à vérification indépendante.", source: "Source ouverte", view: "Voir la source", items: [["Nigeria", "744 enquêtes de traite ont été signalées; le rapport recommande aussi d’agir contre les recruteurs frauduleux et les frais payés par les travailleurs.", "https://www.state.gov/reports/2025-trafficking-in-persons-report/nigeria"], ["Cameroun", "146 affaires de traite ont été enquêtées; un schéma de cybercriminalité aurait attiré des personnes par des offres d’emploi avant une exploitation au travail.", "https://www.state.gov/reports/2025-trafficking-in-persons-report/cameroon"], ["Sénégal", "Le rapport décrit le recrutement frauduleux pour l’emploi à l’étranger, le travail forcé et la criminalité forcée dans des opérations d’arnaque en ligne.", "https://www.state.gov/reports/2025-trafficking-in-persons-report/senegal"], ["Afrique subsaharienne", "Le rapport régional 2024 de l’ONUDC documente des schémas de traite dans une région où les cas sont sous-déclarés.", "https://www.unodc.org/documents/data-and-analysis/glotip/2024/SubSaharanAfrica_GLOTIP2024.pdf"]] },
  SW: { eyebrow: "Kwa nini ni muhimu · picha ya kikanda yenye ushahidi", title: "Ulaghai wa uhamiaji si tatizo la nchi moja.", body: "Katika Afrika Kusini mwa Sahara, uajiri wa udanganyifu, ahadi bandia za uhamiaji, biashara ya binadamu na unyonyaji huingiliana na ukosefu wa taarifa, ulinzi mdogo wa waathirika na njia za kuvuka mipaka. PSP huchukulia ushahidi wa umma kama ishara, si hukumu.", coverage: "Ishara zilizoandikwa katika eneo", caveat: "Hii si sensa kamili ya malalamiko. Taarifa za mitandao ya kijamii huchukuliwa kama vidokezo hadi zithibitishwe kwa uhuru.", source: "Chanzo wazi", view: "Tazama chanzo", items: [["Nigeria", "Ripoti ilirekodi uchunguzi 744 wa biashara ya binadamu na kupendekeza hatua dhidi ya waajiri wa udanganyifu.", "https://www.state.gov/reports/2025-trafficking-in-persons-report/nigeria"], ["Cameroon", "Mamlaka zilichunguza kesi 146; mpango wa uhalifu mtandaoni uliripotiwa kuwavuta watu kwa ahadi za ajira na kuwanyanyasa kazini.", "https://www.state.gov/reports/2025-trafficking-in-persons-report/cameroon"], ["Senegal", "Ripoti inaeleza uajiri wa udanganyifu kwa ajira nje ya nchi, kazi ya kulazimishwa na uhalifu wa kulazimishwa kwenye vituo vya utapeli mtandaoni.", "https://www.state.gov/reports/2025-trafficking-in-persons-report/senegal"], ["Afrika Kusini mwa Sahara", "Ripoti ya UNODC ya 2024 inaonyesha mifumo ya biashara ya binadamu katika eneo lenye taarifa pungufu na zisizo sawa.", "https://www.unodc.org/documents/data-and-analysis/glotip/2024/SubSaharanAfrica_GLOTIP2024.pdf"]] },
};
export default function RegionalEvidence({ language }: { language: Language }) { const t = content[language]; return <section className="bg-[#fffaf0] py-16 sm:py-24"><div className="container"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#9b741e]">{t.eyebrow}</p><h2 className="mt-4 font-display text-4xl font-semibold leading-tight text-[#10202f] sm:text-5xl">{t.title}</h2><p className="mt-6 text-sm leading-7 text-slate-600">{t.body}</p><div className="mt-7 flex gap-3 rounded-2xl border border-[#d9ad3b]/30 bg-white p-5"><Database size={19} className="mt-0.5 shrink-0 text-[#9b741e]" /><p className="text-xs leading-6 text-[#6f5823]">{t.caveat}</p></div></div><div><div className="mb-4 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-[#1c8d68]"><ShieldAlert size={15} />{t.coverage}</div><div className="grid gap-3 sm:grid-cols-2">{t.items.map(([country, text, url]) => <article key={country} className="rounded-2xl border border-[#ecdcae] bg-white p-5"><div className="flex justify-between"><h3 className="font-display text-xl font-semibold text-[#10202f]">{country}</h3><AlertTriangle size={16} className="text-[#d9ad3b]" /></div><p className="mt-4 text-sm leading-6 text-slate-600">{text}</p><a href={url} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-1 text-[10px] font-bold uppercase text-[#1c8d68]">{t.view} <ArrowUpRight size={13} /></a></article>)}</div></div></div></div></section>; }
